<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Pass Email</title>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>

    <!-- use the font -->
    <style>
        body {
        	background-color: #eaeaea;
            font-family: 'Roboto', sans-serif;
            font-size: 48px;
        }
        
    </style>
</head>
<body style="margin: 0; padding: 0;">
	<div style="width: 100%; background-color: #eaeaea; ">
	<div border="1px solid black" >
	<table bgcolor="#eaeaea" border="0" cellspacing="0" cellpadding="0" style="table-layout:fixed;border-collapse:separate">
        <tbody>
            <tr>
                <td height="20" class="m_-4195446629692241502smallspacer" style="border-collapse:separate;table-layout:fixed;font-size:1px;line-height:1px">&nbsp;</td>
            </tr>
        </tbody>
    </table>
    <table align="center" cellpadding="0" cellspacing="0" width="50%" style="border-collapse: collapse;padding= 40px;"; bgcolor="#FFFFFF">
        <tr>
            
            <td align="center" style="padding: 40px 0 20px 0;">
            	<img alt="lms.png" src="https://i.imgur.com/VIaF4XQ.png" style="border:0;display:block;outline:0;text-decoration:none; font-size:12px" width="300px" tabindex="0">
            </td>
        </tr>
        <tr>
            <td  style="padding: 10px 30px 40px 30px;">
                <p>Dear, ${to}</p>
                <p>Here are your password:</p>
                <div align="center" style="background-color: #eaeaea; padding: 40px 30px 40px 20px;">
			        <h1><b>${text}</b></h1>
			    </div>
                
            </td>
        </tr>
        <tr>
        	<td style="padding: 10px 30px 40px 30px;">
        	<p>Lawencon-Assets Management System is a Assets Management System managed by PT. Lawencon International</p>
			<p>Thankyou very much for the attention.</p>
        	</td>
        </tr>
        <tr>
            	<td align="center">
            	<img alt="Password Image" src="https://image.freepik.com/free-vector/key-concept-illustration_114360-6305.jpg" style="border:0;display:block;outline:0;text-decoration:none; font-size:12px" width="500px" class="CToWUd a6T" tabindex="0"> 
            	</td>
        </tr>
    </table>
    <table bgcolor="#eaeaea" border="0" cellspacing="0" cellpadding="0" style="table-layout:fixed;border-collapse:separate">
        <tbody>
            <tr>
                <td height="20" class="m_-4195446629692241502smallspacer" style="border-collapse:separate;table-layout:fixed;font-size:1px;line-height:1px">&nbsp;</td>
            </tr>
            
        </tbody>
    </table>
	</div>
     </div>

</body>
</html>